name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Step 1: Version bump (patch)
      - name: Bump version
        id: bump
        run: |
          VERSION_FILE=version.txt
          if [ ! -f $VERSION_FILE ]; then
            echo "1.0.0" > $VERSION_FILE
          fi
          OLD_VERSION=$(cat $VERSION_FILE)
          IFS='.' read -r major minor patch <<< "$OLD_VERSION"
          NEW_VERSION="$major.$minor.$((patch+1))"
          echo $NEW_VERSION > $VERSION_FILE
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add $VERSION_FILE
          git commit -m "Bump version to $NEW_VERSION" || echo "No changes to commit"
          git push

      # Step 2: Build Docker image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')-app:${{ steps.bump.outputs.version }}
          file: ./Dockerfile
